 - name: Import Nginx repository key
   apt_key:
        id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
        url: https://nginx.org/keys/nginx_signing.key
        state: present

 - name: Setup Nginx apt repository
   apt_repository:
        repo: deb http://nginx.org/packages/ubuntu focal nginx
        state: present
 - name: Install Nginx
   apt:
        name: nginx
        state: present
        update_cache: true
 - name: Start Nginx, ensure it automatically starts on boot
   service:
      name: nginx
      enabled: true
      state: started  
 - name: Create www directory
   file:
       path: /srv/www
       state: directory

 - name: Configure nginx
   copy:
      dest: /etc/nginx/conf.d/default.conf
      src: files/default.conf
 - name: Create index.html
   copy:
        dest: /srv/www/index.html
        src: files/index.html

 - name: Download an image of a logo
   get_url:
        dest: /srv/www/SoftServe.svg
        url: https://upload.wikimedia.org/wikipedia/commons/e/e3/SoftServe.svg
   notify: restart nginx     

